### ISSUE TITLE
Crashing on iOS 9

### ISSUE THREAD

**Issue by mergesort** [foursquare/FSQLocationBroker#4]
I'm getting a crash on this line when I try and run my app on iOS 9.

https://github.com/foursquare/FSQLocationBroker/blob/master/FSQLocationBroker.m#L83

I'm guessing that it might be related to the fact that I only have in-app location permissions turned on, not enabling backgrounding permissions, which this would override.

**Comment by bdorfman** [comment]
Ah, I didn't realize that call is an exception if you don't have the matching entitlements. We'll work up a fix, sorry about that.

**Comment by bdorfman** [comment]
I've pushed a few fixes and improvements for iOS 9. Let me know if things seem to be working for you. I will be pushing a new version'd release soon after a bit more testing.

**Comment by bdorfman** [comment]
Version 1.2.0 is now pushed which should fix this issue.

**Comment by mergesort** [comment]
Yep, confirmed, crashes are fixed. Thanks @bdorfman!
