### ISSUE TITLE
iOS 9 allowsBackgroundLocationUpdates

### ISSUE THREAD

**Issue by bogdantmm92** [foursquare/FSQLocationBroker#5]
I'm having problems using the library in iOS 9. From my investigations something has changed with allowsBackgroundLocationUpdates. I'll dig deeper into the error and post a solution.
http://puu.sh/kMde5/edf93699a9.png

**Comment by bdorfman** [comment]
Are you running version 1.2.0? We tried to add in some guards around allowsBackgroundLocationUpdates so we wouldn't set in the cases the system threw exceptions.

**Comment by bdorfman** [comment]
Any update on this from your end? I am having a hard time reproducing this, as the latest version seems to work for us and a few other people I've checked with.

**Comment by bogdantmm92** [comment]
Hi, sorry for the slow response. The problem in my case is that I needed to add "App registers for location updates" as "required background modes", in iOS 9. It wasn't necessary for older versions.
